### ISSUE TITLE
DYLP222A LS when TC expected

### ISSUE THREAD

**Issue by fredericpiesschaert** [DOV-Vlaanderen/groundwater-logger-validation#41]
The second levelshift seems to be a temporal change to me. Source file: https://github.com/DOV-Vlaanderen/groundwater-logger-validation/commit/aa8dc75889a4ca47b7e3d81a29fab4fa2eb6238b
![image](https://user-images.githubusercontent.com/9843453/69227373-01148f00-0b82-11ea-9ebd-5c5ed08e81f6.png)

**Comment by DavorJ** [comment]
Good example. Seems related to (cf. presentation):
![image](https://user-images.githubusercontent.com/4161918/69234132-ab92af00-0b8e-11ea-9ddf-a4d95d52d15c.png)

In think in your particular case, the reason why it is a LS and not TC, is because it stays low for several points (LS), and then gradually starts decaying (TC). Exponential decal is strongest at the start, so TC doesn't fit well for the first couple of points where the decay effect should be strongest.

**Comment by fredericpiesschaert** [comment]
aha, that makes sense indeed. Perhaps a nice example to add to the documentation? It is an eye-opener to me.
